### ISSUE TITLE
Method names should be in snake case

### ISSUE THREAD

**Issue by sgtpepper43** [mweibel/facebook.ex#45]
By convention, method names should be in `snake_case`, see https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Naming%20Conventions.md#casing
> Elixir developers **must** use snake_case when defining variables, function names, module attributes, etc

It's super weird to use your library when it's the only one using camel case.

**Comment by mweibel** [comment]
Ok, sounds right to change it 😄  I'd merge such a pull request.

**Comment by sgtpepper43** [comment]
Cool cool, for some reason I expected a _lot_ more pushback (developers are notorious for having very strong opinions on very small things, like casing :grimacing: which is why this issue is basically just copying and pasting from the language docs). Even though it'll be a breaking change, since `Graph` is public everyone stuck on an older version can still use the whole graph api, so it shouldn't be too big a deal.

**Comment by mweibel** [comment]
sure, that would be the usual response (from myself included) ;) Thing is: I started with this lib when nothing like that was defined and I just stuck to whatever I thought is best. Now that there are clear naming conventions (and I've seen that there will be soon an official `mix format` command), we should all stick to them to make DX better ;)

About the BC change: we're still in `0.x` phase so that's to be expected. People hopefully have their dependency to facebook.ex correctly set so that this wouldn't break their app when doing a fresh install.

**Comment by paulruescher** [comment]
Mostly fixed in #49. Safe to close this now?
